### ISSUE TITLE
Dead man's snitch addition request

### ISSUE THREAD

**Issue by sudarshan-reddy** [nileshr/airbender-api-monitor#1]
@nileshr 
The api will continue to hold last state even when/if the `raspberrypi` is down. Can you add a feature that compares the parsed time and throws an alert if that value is greater than a constant time interval?

But also keep the api dead check.

**Comment by nileshr** [comment]
Sorry for the delayed response.
Since I'm using Heroku scheduler to run this job at a recurring interval, the app loses it state after it runs. But the problem that'll occur with this approach, is once an API is down, it'll keep spamming that the API is down.
Will put in a fix for this by probably persisting the timestamp and notified state in a db.
